version: '3.8'

services:
  nexus-cleanup:
    build: .
    environment:
      - NEXUS_URL=${NEXUS_URL}
      - NEXUS_USER=${NEXUS_USER}
      - NEXUS_PASS=${NEXUS_PASS}
      - REPOSITORY_NAME=${REPOSITORY_NAME}
      - RETAIN_COUNT=${RETAIN_COUNT}
      - DRY_RUN=${DRY_RUN}
      - LOG_LEVEL=${LOG_LEVEL}
      - SCHEDULE_TIME=${SCHEDULE_TIME}
      - HEALTHCHECK_PORT=${HEALTHCHECK_PORT}
    volumes:
      - nexus-cleanup-logs:/var/log
    ports:
      - "${HEALTHCHECK_PORT}:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      nexus:
        condition: service_healthy

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  nexus-data:
  nexus-cleanup-logs: