version: '3.8'

services:
  nexus-cleanup:
    image: ghcr.io/freemankevin/clean-snapshots/nexus-cleanup:sha-03f11ee
    environment:
      NEXUS_URL: "${NEXUS_URL:-http://nexus:8081}"
      NEXUS_USER: "${NEXUS_USER:-admin}"
      NEXUS_PASS: "${NEXUS_PASS:-admin123}"
      REPOSITORY_NAME: "${REPOSITORY_NAME:-maven-snapshots}"
      RETAIN_COUNT: "3"
      DRY_RUN: "false"
      LOG_LEVEL: "INFO"
      SCHEDULE_TIME: "03:00"
    volumes:
      - nexus-cleanup-logs:/var/log
    ports:
      - "${HEALTHCHECK_PORT}:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      nexus:
        condition: service_healthy

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  nexus-data:
  nexus-cleanup-logs:
    driver: local
    driver_opts:
      type: none
      device: /var/log/nexus-cleanup
      o: bind